src/Entity/Order.php
<?php

namespace App\Entity;

use App\Enum\OrderStatusEnum;
use App\Repository\OrderRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OrderRepository::class)]
#[ORM\Table(name: '`order`')]
class Order
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Company $company = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    /**
     * @var Collection<int, OrderPartial>
     */
    #[ORM\OneToMany(targetEntity: OrderPartial::class, mappedBy: 'foodOrder', orphanRemoval: true, cascade: ['persist', 'remove'])]
    private Collection $orderPartials;

    #[ORM\Column]
    private ?\DateTime $created = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTime $done = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $customerNote = null;

    #[ORM\Column(enumType: OrderStatusEnum::class)]
    private ?OrderStatusEnum $status = null;

    #[ORM\Column(nullable: true)]
    private ?float $rating = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $rating_text = null;

    #[ORM\Column(length: 10)]
    private ?string $deliveryZip = null;

    #[ORM\Column(length: 60)]
    private ?string $deliveryCity = null;

    #[ORM\Column(length: 60)]
    private ?string $deliveryStreet = null;

    #[ORM\Column(length: 4)]
    private ?string $deliverySn = null;

    public function __construct()
    {
        $this->orderPartials = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCompany(): ?Company
    {
        return $this->company;
    }

    public function setCompany(Company $company): static
    {
        $this->company = $company;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(User $user): static
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, OrderPartial>
     */
    public function getOrderPartials(): Collection
    {
        return $this->orderPartials;
    }

    public function addOrderPartial(OrderPartial $orderPartial): static
    {
        if (!$this->orderPartials->contains($orderPartial)) {
            $this->orderPartials->add($orderPartial);
            $orderPartial->setFoodOrder($this);
        }

        return $this;
    }

    public function removeOrderPartial(OrderPartial $orderPartial): static
    {
        if ($this->orderPartials->removeElement($orderPartial)) {
            // set the owning side to null (unless already changed)
            if ($orderPartial->getFoodOrder() === $this) {
                $orderPartial->setFoodOrder(null);
            }
        }

        return $this;
    }

    public function getCreated(): ?\DateTime
    {
        return $this->created;
    }

    public function setCreated(\DateTime $created): static
    {
        $this->created = $created;

        return $this;
    }

    public function getDone(): ?\DateTime
    {
        return $this->done;
    }

    public function setDone(?\DateTime $done): static
    {
        $this->done = $done;

        return $this;
    }

    public function getCustomerNote(): ?string
    {
        return $this->customerNote;
    }

    public function setCustomerNote(?string $customerNote): static
    {
        $this->customerNote = $customerNote;

        return $this;
    }

    public function getStatus(): ?OrderStatusEnum
    {
        return $this->status;
    }

    public function setStatus(OrderStatusEnum $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getRating(): ?float
    {
        return $this->rating;
    }

    public function setRating(?float $rating): static
    {
        $this->rating = $rating;

        return $this;
    }

    public function getRatingText(): ?string
    {
        return $this->rating_text;
    }

    public function setRatingText(?string $rating_text): static
    {
        $this->rating_text = $rating_text;

        return $this;
    }

    public function getDeliveryZip(): ?string
    {
        return $this->deliveryZip;
    }

    public function setDeliveryZip(string $deliveryZip): static
    {
        $this->deliveryZip = $deliveryZip;

        return $this;
    }

    public function getDeliveryCity(): ?string
    {
        return $this->deliveryCity;
    }

    public function setDeliveryCity(string $deliveryCity): static
    {
        $this->deliveryCity = $deliveryCity;

        return $this;
    }

    public function getDeliveryStreet(): ?string
    {
        return $this->deliveryStreet;
    }

    public function setDeliveryStreet(string $deliveryStreet): static
    {
        $this->deliveryStreet = $deliveryStreet;

        return $this;
    }

    public function getDeliverySn(): ?string
    {
        return $this->deliverySn;
    }

    public function setDeliverySn(string $deliverySn): static
    {
        $this->deliverySn = $deliverySn;

        return $this;
    }
}

templates/components/CompanyForm.html.twig
<div {{ attributes }} >
    {{ form_start(form, {
        attr: {
            'data-action': 'blur->live#update',
            'enctype': 'multipart/form-data',
        }
    }) }}
        {{ form_row(form.name) }}
        {{ form_row(form.email) }}
        {{ form_row(form.type) }}
        {{ form_row(form.zip) }}
        {{ form_row(form.city) }}
        {{ form_row(form.street) }}
        {{ form_row(form.sn) }}
        {{ form_row(form.phone) }}
        {{ form_row(form.website) }}
        {{ form_row(form.tax) }}
        <HR />
        <div
            class="mb-3"
            {{ stimulus_controller('company-delivery-zips') }}
        >
            <label for="company_form_delivery_zipcodes" class="form-label required">
                Delivery zipcodes*
            </label>
            <input
                id="company_form_delivery_zipcodes"
                class="form-control mb-3"
                placeholder="Enter your delivery zipcodes here..."
                {{
                    stimulus_target('company-delivery-zips', 'zipInput') |
                    stimulus_action('company-delivery-zips', 'queryZips')
                }}
                
            />
            <div
                class="alert alert-danger mt-2 d-none"
                role="alert"
                {{ stimulus_target('company-delivery-zips', 'errorMsg') }}
            ></div>
            <div
                class="mb-3 zip-dropdown"
                {{ stimulus_target('company-delivery-zips', 'resultContainer') }}
            ></div>
            <label for="company_form_selected_zipcodes" class="form-label required">
                Selected zipcodes
            </label>
            <div
                id="company_form_selected_zipcodes"
                {{ stimulus_target('company-delivery-zips', 'selectedContainer') }}
                class="form-control"
                data-live-ignore
            ></div>
            {{ form_row(form.deliveryZips, {
                attr: {
                    'data-company-delivery-zips-target': 'deliveryZips'
                }
            }) }}
        </div>
        
        <HR />
        {% if form.vars.value.logo %}
            <img
                src="{{ form.vars.value.logo }}?v={{ random() }}"
                style="width: 150px; border-radius: 75px;"
                loading="eager"
            />
        {% else %}
            Logo unset
        {% endif %}
        <BR />
        <BR />
        {{ form_row(form.logo) }}
        <HR />
        {% if status is defined and status != 3 and message is defined and message != '' %}
            <BR />
            <div class="alert {{ status is same as(1) ? 'alert-success' : 'alert-danger' }}">{{ message }}</div>
            {% if status == 1 %}
                <a
                    href="{{ path('company') }}"
                    {{
                            stimulus_controller('reload-form')
                            |
                            stimulus_target('reload-form', 'reloadLink')
                    }}
                    style="display: none;"
                ></a>
            {% endif %}
        {% endif %}
        <button
                id="companySaveBtn"
                type="button"
                class="btn btn-primary {{ not this.validForm ? 'disabled-btn' : '' }}"
                data-action="live#action"
                data-live-action-param="files|save"
                data-loading="addClass(disabledBtn) addAttribute(disabled)"
                data-button-type="formSubmit"
        >Save</button>
    {{ form_end(form) }}
    
    
</div>

templates/components/CreateProduct.html.twig
<div {{ attributes }}>
    {{ form_start(form, {
            attr: {
                'data-action': 'blur->live#update',
                'enctype': 'multipart/form-data',
                'data-controller': 'tooltip-initiator',
            }
        }
    ) }}
        {{ form_row(form.name) }}
        {{ form_row(form.description) }}
        {{ form_row(form.price) }}
        {{ form_row(form.category) }}
        {{ form_row(form.type) }}
        <HR />
        <p>
            Add the available sizes for this dish:
            <span
                data-bs-toggle="tooltip"
                data-bs-placement="top"
                data-bs-custom-class="custom-tooltip"
                data-bs-title="Enter a price other than 0 to make a size available. Please note that the given size prices are additional to the standard price."
            ><i class="bi bi-question-circle"></i></span>
        </p>
        {% for sizeField in form.sizes %}
            {% if loop.index0 % 3 == 0 %}
                <div class="row">
            {% endif %}
                    <div class="col" style="min-width: 150px;">
                        <div class="form-group">            
                            <div class="input-group mb-3">
                                <span class="input-group-text" id="dish-size-{{ sizeField.vars.name }}">{{ sizeField.vars.name }}</span>
                                {{
                                    form_widget(
                                        sizeField,
                                        {
                                            'attr': {
                                                'class': 'form-control',
                                                'placeholder': sizeField.vars.name,
                                                'aria-label': 'Dish size ' ~ sizeField.vars.name,
                                                'aria-describedby': 'dish-size-' ~ sizeField.vars.name,
                                                'max': '99.9',
                                                'step': 'any',
                                            }
                                        }
                                    )
                                }}
                            </div>
                            {{ form_errors(sizeField) }}
                        </div>
                    </div>
            {% if loop.index0 % 3 == 2 %}
                </div>
            {% endif %}
        {% endfor %}
        <HR />

        {# Extras #}
        <label for="dish-extras-selected-container" class="form-label required me-3">
            Extras
        </label>
        <span
            class="btn btn-primary btn-sm me-3"
            data-bs-toggle="modal"
            data-bs-target="#dish-extras-modal"
            {{ stimulus_action('extras', 'openExtraModal', 'click') }}
        >Add extra</span>
        <span
            class="btn btn-primary btn-sm"
            data-bs-toggle="modal"
            data-bs-target="#dish-extras-modal"
            {{ stimulus_action('extras', 'openGroupModal', 'click') }}
        >Manage Groups</span>
        <div
            id="dish-extras-selected-container"
            {{ stimulus_target('extras', 'selectedContainer') }}
            class="form-control select-container-with-divider"
            data-live-ignore
        >
            <div
                {{ stimulus_target('extras', 'extrasMultiContainer') }}
                class="extrasContainerClass"
            ></div>
            <div class="select-container-divider"></div>
            <div
                {{ stimulus_target('extras', 'extrasSingleContainer') }}
                class="extrasContainerClass"
            >
                <div id="extras-single-group-Default" class="mb-3">
                    <h5 class="text-center fw-bold">Default</h5>
                    <HR />
                    <div id="extras-single-group-sub-container-Default"></div>
                </div>
            </div>
        </div>
        {{ form_row(form.extras, {
            attr: {
                'data-extras-target': 'extras'
            }
        }) }}
        <HR />

        {# Image #}
        {% if form.vars.value.img %}
            <img
                src="{{ form.vars.value.img }}?v={{ random() }}"
                style="width: 150px; border-radius: 75px;"
                loading="eager"
            />
        {% else %}
            Product image unset
        {% endif %}
        <BR />
        <BR />
        {{ form_row(form.img) }}
        <HR />
        {% if status is defined and status != 3 and message is defined and message != '' %}
            <BR />
            <div class="alert {{ status is same as(1) ? 'alert-success' : 'alert-danger' }}">{{ message }}</div>
            {% if status == 1 %}
                <a
                    href="{{ path('create_product') }}"
                    {{
                            stimulus_controller('reload-form')
                            |
                            stimulus_target('reload-form', 'reloadLink')
                    }}
                    style="display: none;"
                ></a>
            {% endif %}
        {% endif %}
        <BR />
        <button
                id="createProductSaveBtn"
                type="button"
                class="btn btn-primary {{ not this.isValidForm ? 'disabled-btn' : '' }}"
                data-action="live#action"
                data-live-action-param="files|save"
                data-loading="addClass(disabledBtn) addAttribute(disabled)"
                data-button-type="formSubmit"
        >Save</button>
    {{ form_end(form) }}
</div>

templates/components/DeleteProduct.html.twig
<div{{ attributes }}>
    <button
        {{ stimulus_action('dish', 'delete') }}
    >
        Delete
    </button>
    <button
        id="delete-dish-{{ dishId }}"
        data-action="click->live#action"
        data-live-action-param="delete"
        data-live-dish-id-param="{{ dishId }}"
        class="d-none"
    ></button>
    <span id="delete-dish-response-{{ dishId }}"></span>
</div>

templates/components/DishFilter.html.twig
<div{{ attributes }}>
    <input type="text" class="form-control" data-model="debounce(250)|filter" placeholder="Filter your dishes by name, category or type" />
    <BR />
    <div
        id="dish-cards"
        {{stimulus_controller('dish-cards')}}
    >
        {% for dish in this.dishes %}
            <div
                class="dish-card"
                data-dish-id="{{dish.id}}"
                {{ stimulus_controller('dish', { id: dish.id }) }}
            >
                <img src="/{{dish.img}}" alt="{{dish.name}}" style="width:100%" />
                <div class="dish-card-header">
                    <h1>{{dish.name|u.truncate(23, '...')}}</h1>
                </div>
                <p class="dish-price">{{dish.price | format_currency('USD', {decimal_always_shown:true}, 'en') }}</p>
                <p id="dish-desc-{{dish.id}}" class="dish-card-desc">{{dish.description}}</p>
                <div class="dish-card-buttons">
                    <p>
                        <button
                            {{ stimulus_action('dish', 'view') }}
                            data-bs-toggle="modal"
                            data-bs-target="#dish-modal"
                        >
                            Preview
                        </button>
                    </p>
                    <p>
                        <button
                            {{ stimulus_action('dish', 'edit') }}
                            data-bs-toggle="modal"
                            data-bs-target="#dish-modal"
                        >
                            Edit
                        </button>
                    </p>
                    <p>
                        {% component DeleteProduct with {
                            dishId: dish.id
                        } %}
                        {% endcomponent %}
                    </p>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

templates/components/EditProduct.html.twig
<div {{ attributes }}>
    {{ form_start(form, {
            attr: {
                'data-action': 'blur->live#update',
                'enctype': 'multipart/form-data',
            }
        }
    ) }}
        {{ form_row(form.name) }}
        {{ form_row(form.description) }}
        {{ form_row(form.price) }}
        {{ form_row(form.category) }}
        {{ form_row(form.type) }}
        <HR />
        <p>
            Add the available sizes for this dish:
            <span
                data-bs-toggle="tooltip"
                data-bs-placement="top"
                data-bs-custom-class="custom-tooltip"
                data-bs-title="Enter a price other than 0 to make a size available. Please note that the given size prices are additional to the standard price."
            ><i class="bi bi-question-circle"></i></span>
        </p>
        {% for sizeField in form.sizes %}
            {% if loop.index0 % 3 == 0 %}
                <div class="row">
            {% endif %}
                    <div class="col" style="min-width: 150px;">
                        <div class="form-group">            
                            <div class="input-group mb-3">
                                <span class="input-group-text" id="dish-size-{{ sizeField.vars.name }}">{{ sizeField.vars.name }}</span>
                                {{
                                    form_widget(
                                        sizeField,
                                        {
                                            'attr': {
                                                'class': 'form-control',
                                                'placeholder': sizeField.vars.name,
                                                'aria-label': 'Dish size ' ~ sizeField.vars.name,
                                                'aria-describedby': 'dish-size-' ~ sizeField.vars.name,
                                                'max': '99.9',
                                                'step': 'any',
                                            }
                                        }
                                    )
                                }}
                            </div>
                            {{ form_errors(sizeField) }}
                        </div>
                    </div>
            {% if loop.index0 % 3 == 2 %}
                </div>
            {% endif %}
        {% endfor %}
        <HR />

        {# Extras #}
        <label for="dish-extras-selected-container" class="form-label required me-3">
            Extras
        </label>
        <span
            class="btn btn-primary btn-sm me-3"
            data-bs-target="#dish-extras-modal"
            {{ stimulus_action('extras', 'openExtraModal', 'click') }}
        >Add extra</span>
        <span
            class="btn btn-primary btn-sm"
            data-bs-target="#dish-extras-modal"
            {{ stimulus_action('extras', 'openGroupModal', 'click') }}
        >Manage Groups</span>
        <div
            id="dish-extras-selected-container"
            {{ stimulus_target('extras', 'selectedContainer') }}
            class="form-control select-container-with-divider"
            data-live-ignore
        >
            <div
                {{ stimulus_target('extras', 'extrasMultiContainer') }}
                class="extrasContainerClass"
            ></div>
            <div class="select-container-divider"></div>
            <div
                {{ stimulus_target('extras', 'extrasSingleContainer') }}
                class="extrasContainerClass"
            >
                <div id="extras-single-group-Default" class="mb-3">
                    <h5 class="text-center fw-bold">Default</h5>
                    <HR />
                    <div id="extras-single-group-sub-container-Default"></div>
                </div>
            </div>
        </div>
        {{ form_row(form.extras, {
            attr: {
                'data-extras-target': 'extras',
            }
        }) }}
        <HR />

        <HR />
        {% if form.vars.value.img %}
            <img
                src="/{{ form.vars.value.img }}?v={{ random() }}"
                style="width: 150px; border-radius: 75px;"
                loading="eager"
            />
        {% elseif preserveImg %}
            <img
                src="/{{ preserveImg }}?v={{ random() }}"
                style="width: 150px; border-radius: 75px;"
                loading="eager"
            />
        {% else %}
            Product image unset
        {% endif %}
        <BR />
        <BR />
        {{ form_row(form.img) }}
        <HR />
        {% if status is defined and status != 3 and message is defined and message != '' %}
            <BR />
            <div class="alert {{ status is same as(1) ? 'alert-success' : 'alert-danger' }}">{{ message }}</div>
            {% if status == 1 %}
                <div class="d-none" {{ stimulus_controller('close-modal', {
                    modalId: 'dish-modal',
                    timeout: 5000
                }) }}>
            {% endif %}
        {% endif %}
        <BR />
        <button
                id="updateProductSaveBtn"
                type="button"
                class="btn btn-primary {{ not this.isValidForm ? 'disabled-btn' : '' }}"
                data-action="live#action"
                data-live-action-param="files|update"
                data-loading="addClass(disabledBtn) addAttribute(disabled)"
                data-button-type="formSubmit"
        >Update</button>
    {{ form_end(form) }}
</div>

templates/components/EditUser.html.twig
<div{{ attributes }}>
    {{
        form_start (
            form, {
                attr: {
                    'data-action': 'blur->live#update',
                    'enctype': 'multipart/form-data',
                }
            }
        )
    }}
        {{ form_row(form.email) }}
        {{ form_row(form.forename) }}
        {{ form_row(form.surname) }}
        {{ form_row(form.street) }}
        {{ form_row(form.sn) }}
        {{ form_row(form.zipcode) }}
        {{ form_row(form.city) }}
        {{ form_row(form.currentPassword) }}
    {{ form_end(form) }}

    {% if status is defined and message is defined %}
        {% if status == 200 and message != '' %}
            <div class="alert alert-success" role="alert">
                {{ message }}
            </div>
            <a
                href="{{ path('edit_user') }}"
                {{
                        stimulus_controller('reload-form')
                        |
                        stimulus_target('reload-form', 'reloadLink')
                }}
                style="display: none;"
            ></a>
        {% elseif message != '' %}
            <div class="alert alert-danger" role="alert">
                {{ message }}
            </div>
            {% if errors | length > 0 %}
                {% for error in errors %}
                    <div class="alert alert-danger" role="alert">
                        {{ error }}
                    </div>
                {% endfor %}
            {% endif %}
        {% endif %}
    {% endif %}
    <input type="hidden" name="token_delete" value="{{ csrf_token('delete-user') }}">
    <button
        class="btn btn-primary"
        data-action="live#action"
        data-live-action-param="save"
        type="button"
    >
        Submit
    </button>
    <HR />
    <button
        class="btn btn-danger"
        {{
            stimulus_controller('delete-user') |
            stimulus_action('delete-user', 'delete')
        }}
    >
        Delete account
    </button>
</div>

templates/components/ExtraFinder.html.twig
<div{{ attributes }}>
    <div class="input-group">
        <span
            class="input-group-text"
            id="extra-add-name-input-label"
            data-bs-toggle="tooltip"
            data-bs-placement="top"
            data-bs-custom-class="custom-tooltip"
            data-bs-title="You can select one name from the dropdown if it exists already."
        ><i class="bi bi-question-circle"></i></span>
        <div class="form-floating">
            <input
                type="search"
                id="extra-add-name-input"
                class="form-control"
                placeholder="Give your extra a name"
                aria-label="Extra name"
                aria-describedby="extra-add-name-input-label"
                data-model="debounce(500)|extraName"
                autocomplete="off"
                {{ stimulus_target('extras', 'extraNameInput') }}
            />
            <label for="extra-add-name-input">Give your extra a name</label>
        </div>
    </div>
    <ul
        {{ stimulus_target('extras', 'extraNamesSuggestion') }}
        class="dropdown-menu {{ extras | length > 0 ? 'd-block' : 'd-none' }}"
        style="width: 100%;"
    >
    {% for extra in extras %}
        <li>
            <span
                class="dropdown-item cursor-pointer"
                {{ stimulus_action('extras', 'autoFillExtraName', 'click', {'name': extra.name}) }}
            >
                {{ extra.name }}
            </span>
        </li>
    {% endfor %}
    </ul>
    <div class="input-group mt-3">
        <span
            class="input-group-text"
            id="extra-add-price-input-label"
            data-bs-toggle="tooltip"
            data-bs-placement="top"
            data-bs-custom-class="custom-tooltip"
            data-bs-title="Only use an additional charge, not the total price of the dish with that extra."
        ><i class="bi bi-question-circle"></i></span>
        <div class="form-floating">
            <input
                type="search"
                id="extra-add-price-input"
                class="form-control"
                placeholder="Set a price for this extra"
                aria-label="Extra price"
                aria-describedby="extra-add-price-input-label"
                autocomplete="off"
                {{ stimulus_target('extras', 'extraPriceInput') }}
            />
            <label for="extra-add-price-input">Set a price for this extra</label>
        </div>
    </div>
</div>

templates/components/ShowRatings.html.twig
<div{{ attributes.defaults(stimulus_controller('show-ratings')) }}>
    {% set orders = this.orders %}
    {% if orders | length > 0 %}
        {% if page > 1 %}
            <div id="ratings-page-{{ page - 1 }}" data-live-ignore="true"></div>
        {% endif %}
        <div id="ratings-page-{{ page }}" data-live-ignore="true">
                {% for order in this.orders %}
                    <div style="height: 100%;">
                        <h5>{{ order.user.deleted ? 'Deleted user' : order.user.forename }} {{ order.user.deleted ? '' : order.user.surname [:1] }}.</h5>
                        <div>
                            {% set totalRating = order.rating %}
                            {% for i in 1..totalRating %}
                                <i class="bi bi-star-fill" style="color: gold;"></i>
                                {% set totalRating = totalRating - 1 %}
                            {% endfor %}
                        </div>
                        <span>{{ order.ratingText }}</span>
                    </div>
                    <HR />
                {% endfor %}
        </div>
        {% if this.hasNextPage %}
            <div
                style="width: 100%; height: 20px;"
                {{
                    stimulus_target('show-ratings', 'loader') |
                    stimulus_action('live', 'action', 'loadMore', { 'action': 'loadMore' })
                }}
            ></div>
        {% endif %}
    {% else %}
        <div class="alert alert-info" role="alert">
            There are no ratings available for this company yet.
        </div>
    {% endif %}
    </div>
</div>